@EasyPizza_API_HostAddress = https://localhost:7182

### Get All

GET {{EasyPizza_API_HostAddress}}/api/Ingredients
Accept: application/json

### Get By Id

GET {{EasyPizza_API_HostAddress}}/api/Ingredients/c5d09959-9823-43b0-a2fe-3f1fa2591cda
Accept: application/json

### Create

POST {{EasyPizza_API_HostAddress}}/api/Ingredients
Content-Type: application/json

{
  "name": "blue cheese",
  "price": 1.23
}

### Update

PUT {{EasyPizza_API_HostAddress}}/api/Ingredients/c5d09959-9823-43b0-a2fe-3f1fa2591cda
Content-Type: application/json

{
  "name": "blue cheese",
  "price": 0.30,
  "deleted": false
}

### Delete

DELETE {{EasyPizza_API_HostAddress}}/api/Ingredients/c5d09959-9823-43b0-a2fe-3f1fa2591cda
Content-Type: application/json

