@EasyPizza_API_HostAddress = https://localhost:7182

### Get All

GET {{EasyPizza_API_HostAddress}}/api/Ingredients
Accept: application/json

### Get By Id

GET {{EasyPizza_API_HostAddress}}/api/Ingredients/15f843f9-bfc0-4bd9-940c-2ec7913865e3
Accept: application/json

### Create

POST {{EasyPizza_API_HostAddress}}/api/Ingredients
Content-Type: application/json

{
  "name": "cheese",
  "price": 1.23
}

### Update

PUT {{EasyPizza_API_HostAddress}}/api/Ingredients/7f013999-fae4-432d-85df-8fdfc184bdee
Content-Type: application/json

{
  "name": "brown pepper",
  "price": 0.30,
  "deleted": false
}

### Delete

DELETE {{EasyPizza_API_HostAddress}}/api/Ingredients/7f013999-fae4-432d-85df-8fdfc184bdee
Content-Type: application/json

