@EasyPizza_API_HostAddress = https://localhost:7182
@NoClaimToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxOTFmOTAyNi02MWRkLTQ3N2UtYWU2Ny0wZjVlMzI5ODY2MzciLCJzdWIiOiJ3aW1AbWFpbC5jb20iLCJlbWFpbCI6IndpbUBtYWlsLmNvbSIsInVzZXJpZCI6IjgyYjMyZThiLTQ3MDctNGFhNS04ZjQ5LTA5YjhiYzllMzI1MiIsImFkbWluIjpmYWxzZSwidHJ1c3RlZF9tZW1iZXIiOmZhbHNlLCJuYmYiOjE3Mzg2Nzc2NzUsImV4cCI6MTczODcwNjQ3NSwiaWF0IjoxNzM4Njc3Njc1LCJpc3MiOiJodHRwczovL2Vhc3lwaXp6YS5pZC5jb20iLCJhdWQiOiJodHRwczovL2Vhc3lwaXp6YS5jb20ifQ.JcOz1oPy55DsAjTVXk-IF4ZMdpiox5r3jNtONHTY7Vs
@TrustedUserToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4NjdmNWJkNS1mZGY0LTQyZDUtYTY0ZS0yZWI0Mzk4NjlhODQiLCJzdWIiOiJ3aW1AbWFpbC5jb20iLCJlbWFpbCI6IndpbUBtYWlsLmNvbSIsInVzZXJpZCI6IjgyYjMyZThiLTQ3MDctNGFhNS04ZjQ5LTA5YjhiYzllMzI1MiIsImFkbWluIjpmYWxzZSwidHJ1c3RlZF9tZW1iZXIiOnRydWUsIm5iZiI6MTczODY3NzY5MywiZXhwIjoxNzM4NzA2NDkzLCJpYXQiOjE3Mzg2Nzc2OTMsImlzcyI6Imh0dHBzOi8vZWFzeXBpenphLmlkLmNvbSIsImF1ZCI6Imh0dHBzOi8vZWFzeXBpenphLmNvbSJ9.xYZ3HTxakyGU8u2OHcpwBzc2Z7Cjb89K283GO9t-nVo
@AdminToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3MGZmYjkzYi00OTQ0LTQwMWYtOTQ5Mi1hZTRlNTY2ZmQ5NGYiLCJzdWIiOiJ3aW1AbWFpbC5jb20iLCJlbWFpbCI6IndpbUBtYWlsLmNvbSIsInVzZXJpZCI6IjgyYjMyZThiLTQ3MDctNGFhNS04ZjQ5LTA5YjhiYzllMzI1MiIsImFkbWluIjp0cnVlLCJ0cnVzdGVkX21lbWJlciI6ZmFsc2UsIm5iZiI6MTczODY3NzIwNywiZXhwIjoxNzM4NzA2MDA3LCJpYXQiOjE3Mzg2NzcyMDcsImlzcyI6Imh0dHBzOi8vZWFzeXBpenphLmlkLmNvbSIsImF1ZCI6Imh0dHBzOi8vZWFzeXBpenphLmNvbSJ9.fnFKa4bVMmR97Y4eJNApl179MNDIepg0aa7dU6Lkqog

### Get All

GET {{EasyPizza_API_HostAddress}}/api/v1/Ingredients
Accept: application/json
Authorization: {{NoClaimToken}} 

### Get By Id

GET {{EasyPizza_API_HostAddress}}/api/v1/Ingredients/c5d09959-9823-43b0-a2fe-3f1fa2591cda
Accept: application/json
Authorization: {{NoClaimToken}}

### Create

POST {{EasyPizza_API_HostAddress}}/api/v1/Ingredients
Content-Type: application/json
Authorization: {{TrustedUserToken}}

{
  "name": "blue cheese",
  "price": 1.23
}

### Update

PUT {{EasyPizza_API_HostAddress}}/api/v1/Ingredients/a015eed6-8127-4c82-ac8c-af6634cd260e
Content-Type: application/json
Authorization: {{TrustedUserToken}}

{
  "name": "blue cheese",
  "price": 0.33,
  "deleted": false
}

### Delete

DELETE {{EasyPizza_API_HostAddress}}/api/v1/Ingredients/a015eed6-8127-4c82-ac8c-af6634cd260e
Content-Type: application/json
Authorization: {{AdminToken}} 

