@EasyPizza_API_HostAddress = https://localhost:7182
@NoClaimToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxOTFmOTAyNi02MWRkLTQ3N2UtYWU2Ny0wZjVlMzI5ODY2MzciLCJzdWIiOiJ3aW1AbWFpbC5jb20iLCJlbWFpbCI6IndpbUBtYWlsLmNvbSIsInVzZXJpZCI6IjgyYjMyZThiLTQ3MDctNGFhNS04ZjQ5LTA5YjhiYzllMzI1MiIsImFkbWluIjpmYWxzZSwidHJ1c3RlZF9tZW1iZXIiOmZhbHNlLCJuYmYiOjE3Mzg2Nzc2NzUsImV4cCI6MTczODcwNjQ3NSwiaWF0IjoxNzM4Njc3Njc1LCJpc3MiOiJodHRwczovL2Vhc3lwaXp6YS5pZC5jb20iLCJhdWQiOiJodHRwczovL2Vhc3lwaXp6YS5jb20ifQ.JcOz1oPy55DsAjTVXk-IF4ZMdpiox5r3jNtONHTY7Vs
@TrustedUserToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI4NjdmNWJkNS1mZGY0LTQyZDUtYTY0ZS0yZWI0Mzk4NjlhODQiLCJzdWIiOiJ3aW1AbWFpbC5jb20iLCJlbWFpbCI6IndpbUBtYWlsLmNvbSIsInVzZXJpZCI6IjgyYjMyZThiLTQ3MDctNGFhNS04ZjQ5LTA5YjhiYzllMzI1MiIsImFkbWluIjpmYWxzZSwidHJ1c3RlZF9tZW1iZXIiOnRydWUsIm5iZiI6MTczODY3NzY5MywiZXhwIjoxNzM4NzA2NDkzLCJpYXQiOjE3Mzg2Nzc2OTMsImlzcyI6Imh0dHBzOi8vZWFzeXBpenphLmlkLmNvbSIsImF1ZCI6Imh0dHBzOi8vZWFzeXBpenphLmNvbSJ9.xYZ3HTxakyGU8u2OHcpwBzc2Z7Cjb89K283GO9t-nVo
@AdminToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3MGZmYjkzYi00OTQ0LTQwMWYtOTQ5Mi1hZTRlNTY2ZmQ5NGYiLCJzdWIiOiJ3aW1AbWFpbC5jb20iLCJlbWFpbCI6IndpbUBtYWlsLmNvbSIsInVzZXJpZCI6IjgyYjMyZThiLTQ3MDctNGFhNS04ZjQ5LTA5YjhiYzllMzI1MiIsImFkbWluIjp0cnVlLCJ0cnVzdGVkX21lbWJlciI6ZmFsc2UsIm5iZiI6MTczODY3NzIwNywiZXhwIjoxNzM4NzA2MDA3LCJpYXQiOjE3Mzg2NzcyMDcsImlzcyI6Imh0dHBzOi8vZWFzeXBpenphLmlkLmNvbSIsImF1ZCI6Imh0dHBzOi8vZWFzeXBpenphLmNvbSJ9.fnFKa4bVMmR97Y4eJNApl179MNDIepg0aa7dU6Lkqog

### Get All

GET {{EasyPizza_API_HostAddress}}/api/v1/orders
Accept: application/json
Authorization: {{NoClaimToken}}

### Get By Id

GET {{EasyPizza_API_HostAddress}}/api/orders/v1/1a9c7bf4-9571-4d8f-a828-b7e56b8022bb
Accept: application/json
Authorization: {{NoClaimToken}}

### Create

POST {{EasyPizza_API_HostAddress}}/api/v1/orders
Content-Type: application/json
Authorization: {{TrustedUserToken}}

{
  "pizzas": [
    {
      "pizzaBase": {
        "id": "0434c226-a2d5-4d2b-9d62-e969a7c62c08",
        "name": "thin crust",
        "size": "Small",
        "price": 1.0
      },
      "pizzaIngredients": [
        {
          "id": "76ad2763-e715-4125-8087-03be7eb00552",
          "name": "salami",
          "price": 2.0
        },
        {
          "id": "16af5c15-3814-4590-a385-897ad7919556",
          "name": "cheese",
          "price": 1.25
        },
        {
          "id": "b3165107-8c02-44ea-86f2-3c31bbe2be5d",
          "name": "green pepper",
          "price": 0.25
        }
      ]
    },
    {
      "pizzaBase": {
        "id": "325f0ea3-ce42-4aec-b0a2-a5d3a43905dc",
        "name": "gluten free",
        "size": "Medium",
        "price": 1.0
      },
      "pizzaIngredients": [
        {
          "id": "76ad2763-e715-4125-8087-03be7eb00552",
          "name": "salami",
          "price": 2.0
        },
        {
          "id": "16af5c15-3814-4590-a385-897ad7919556",
          "name": "cheese",
          "price": 1.25
        }
      ]
    }
  ]
}