@EasyPizza_API_HostAddress = https://localhost:7182

### Get All

GET {{EasyPizza_API_HostAddress}}/api/pizza-bases
Accept: application/json

### Get by Id

GET {{EasyPizza_API_HostAddress}}/api/pizza-bases/a6eb2e84-bed5-47b7-bb1c-b532accd2225
Accept: application/json

### Create

POST {{EasyPizza_API_HostAddress}}/api/pizza-bases
Content-Type: application/json

{
  "name": "Cheese Crust & beer",
  "price": 1.23,
  "size": "MEDIUM"
}

### Update

PUT {{EasyPizza_API_HostAddress}}/api/pizza-bases/a6eb2e84-bed5-47b7-bb1c-b532accd2225
Content-Type: application/json

{
  "name": "cheese crust & beer",
  "price": 1.50,
  "size": "MEDIUM",
  "deleted": true
}

### Delete

DELETE {{EasyPizza_API_HostAddress}}/api/pizza-bases/a6eb2e84-bed5-47b7-bb1c-b532accd2225
Content-Type: application/json