services:
  easypizza.api:
    image: easypizza.api
    build:
      context: .
      dockerfile: src/EasyPizza.Api/Dockerfile
    ports:
      - 8080:8080
        
  identity.api:
    image: identity.api
    build:
      context: .
      dockerfile: src/Identity.Api/Dockerfile
    ports:
      - 80:80

  easypizza.db:
    container_name: easypizza.db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: easypizza
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pizza
    volumes:
      - postgres_data:/var/lib/postresql/data
        
volumes:
  postgres_data: